#!/usr/bin/env bash

# Copy this to examples/ENVIRONMENT, set the variables in that file to your
# sandbox URL and credentials for the user that will be used to make
# authenticated requests.
#
# Get the variables into your environment with `source examples/ENVIRONMENT`.

export ACTINDO_SANDBOX_URL='https://YOUR-SANDBOX.actindo.com/jsonrpc'
export ACTINDO_LOGIN='user'
export ACTINDO_PASSWORD='password'
